all: main
	./main

main:
	clang++ \
		main.cc -o main
		#-isystem /usr/include/c++/11 \
		#-isystem /usr/include/x86_64-linux-gnu/c++/11 \
		#-L/usr/lib/gcc/x86_64-linux-gnu/11 \
 
		#-isystem /usr/lib/gcc/x86_64-linux-gnu/11/include \

